### ISSUE TITLE
Get household calculator working on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/uk-2024-manifestos-comparison#5]
<img width="344" alt="image" src="https://github.com/PolicyEngine/uk-2024-manifestos-comparison/assets/6076111/b4dd5b2c-e807-45a7-8bff-87d2b0d54933">

**Comment by anth-volk** [comment]
Is the issue here only the sizing? Or are there also problems with, e.g., touch events?

**Comment by MaxGhenis** [comment]
i think the sizing also creates problems for touch events, since it takes the whole screen you end up adjusting the graph instead of scrolling
